import React from 'react';
import { fmtNumber } from '../services/format';

export function LineChart({data,series}:{data:{label:string;[key:string]:string|number}[];series:{key:string;label:string}[]}){
  const width=600,height=230,pad=30;const values=data.flatMap(d=>series.map(s=>Number(d[s.key]??0)));const max=Math.max(1,...values);const x=(i:number)=>pad+(data.length<=1?0:i*(width-pad*2)/(data.length-1));const y=(v:number)=>height-pad-(v/max)*(height-pad*2);
  return <div className="lf-chart" role="img" aria-label={`Gráfico de ${series.map(s=>s.label).join(', ')}`}><svg viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none">{[0,.25,.5,.75,1].map(n=><line key={n} className="lf-chart-grid" x1={pad} x2={width-pad} y1={y(max*n)} y2={y(max*n)}/>) }{series.map((s,si)=>{const points=data.map((d,i)=>`${x(i)},${y(Number(d[s.key]??0))}`).join(' ');return <polyline key={s.key} points={points} className="lf-chart-line" style={{stroke:si===0?'var(--lf-color-primary)':si===1?'var(--lf-color-success)':'var(--lf-color-warning)',strokeDasharray:si===2?'5 4':undefined}}/>})}{data.map((d,i)=><text key={i} x={x(i)} y={height-6} textAnchor="middle" className="lf-chart-label">{d.label}</text>)}</svg></div>
}
export function BarList({data}:{data:{label:string;value:number}[]}){const max=Math.max(1,...data.map(d=>d.value));return <div className="lf-bar-list">{data.map(d=><div className="lf-bar-row" key={d.label}><span>{d.label}</span><div className="lf-bar-track"><div className="lf-bar-fill" style={{width:`${d.value/max*100}%`}}/></div><strong className="lf-number">{fmtNumber(d.value)}</strong></div>)}</div>}
const colors=['#0369A1','#1D4ED8','#B45309','#15803D','#B91C1C'];
export function DonutChart({data}:{data:{label:string;value:number}[]}){const total=data.reduce((a,b)=>a+b.value,0);let acc=0;const stops=data.map((d,i)=>{const start=total?acc/total*100:0;acc+=d.value;const end=total?acc/total*100:0;return `${colors[i%colors.length]} ${start}% ${end}%`}).join(', ');return <div className="lf-donut-wrap"><div className="lf-donut" style={{background:total?`conic-gradient(${stops})`:'#E2E8F0'}}><div className="lf-donut-center">{fmtNumber(total)}</div></div><div className="lf-legend">{data.map((d,i)=><div className="lf-legend-item" key={d.label}><span className="lf-legend-dot" style={{background:colors[i%colors.length]}}/><span>{d.label}</span><strong>{fmtNumber(d.value)}</strong></div>)}</div></div>}
