import React, { createContext, useCallback, useContext, useEffect, useId, useState, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes, type TextareaHTMLAttributes } from 'react';
import { fmtNumber } from '../services/format';

export function Button({variant='primary',size='md',className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'tertiary'|'danger';size?:'sm'|'md'|'lg'}){
  return <button className={`lf-btn lf-btn-${variant} ${size==='sm'?'lf-btn-sm':size==='lg'?'lf-btn-lg':''} ${className}`} {...props}/>;
}
export function IconButton({label,children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{label:string;children:ReactNode}){return <button className="lf-icon-btn" aria-label={label} title={label} {...props}>{children}</button>}
export function Card({children,className=''}:{children:ReactNode;className?:string}){return <section className={`lf-card ${className}`}>{children}</section>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'info'|'primary'|'warning'|'success'|'danger'|'neutral'}){return <span className={`lf-badge lf-badge-${tone}`}>{children}</span>}
export function PageHeader({title,description,breadcrumb,actions}:{title:string;description?:string;breadcrumb?:ReactNode;actions?:ReactNode}){return <header className="lf-page-header"><div className="lf-page-header-main">{breadcrumb&&<div className="lf-breadcrumb">{breadcrumb}</div>}<h1 className="lf-page-title">{title}</h1>{description&&<p className="lf-page-description">{description}</p>}</div>{actions&&<div className="lf-page-actions">{actions}</div>}</header>}
export function Field({label,error,helper,children}:{label:string;error?:string;helper?:string;children:ReactNode}){const id=useId();return <div className="lf-field" data-field-id={id}><span className="lf-label">{label}</span>{children}{error&&<span className="lf-field-error" role="alert">{error}</span>}{helper&&!error&&<span className="lf-helper">{helper}</span>}</div>}
export const Input=(props:InputHTMLAttributes<HTMLInputElement>)=><input className={`lf-input ${props.className??''}`} {...props}/>;
export const Select=(props:SelectHTMLAttributes<HTMLSelectElement>)=><select className={`lf-select ${props.className??''}`} {...props}/>;
export const Textarea=(props:TextareaHTMLAttributes<HTMLTextAreaElement>)=><textarea className={`lf-textarea ${props.className??''}`} {...props}/>;
export function EmptyState({title,text,action}:{title:string;text:string;action?:ReactNode}){return <div className="lf-empty"><div className="lf-empty-title">{title}</div><p className="lf-empty-text">{text}</p>{action}</div>}
export function Alert({children,tone='info'}:{children:ReactNode;tone?:'info'|'error'|'warning'}){return <div className={`lf-alert lf-alert-${tone}`} role={tone==='error'?'alert':undefined}>{children}</div>}
export function Skeleton({height=20,width='100%'}:{height?:number;width?:string}){return <div className="lf-skeleton" style={{height,width}}/>}
export function LoadingPanel(){return <Card><div style={{display:'grid',gap:12}}><Skeleton height={24} width="35%"/><Skeleton height={16}/><Skeleton height={16}/><Skeleton height={16} width="80%"/></div></Card>}
export function KpiCard({label,value,variation=0}:{label:string;value:number;variation?:number}){const cls=variation>0?'lf-trend-up':variation<0?'lf-trend-down':'';return <Card className="lf-kpi"><div className="lf-kpi-label">{label}</div><div className="lf-kpi-value">{fmtNumber(value)}</div><div className="lf-kpi-footer"><span className={cls}>{variation>0?'↑':variation<0?'↓':'→'} {Math.abs(variation).toLocaleString('pt-BR',{maximumFractionDigits:1})}%</span><span>vs. período anterior</span></div></Card>}
export function Pagination({page,totalPages,totalElements,onPage}:{page:number;totalPages:number;totalElements:number;onPage:(page:number)=>void}){return <div className="lf-pagination"><span>{fmtNumber(totalElements)} registro{totalElements===1?'':'s'}</span><span className="spacer"/><Button variant="secondary" size="sm" disabled={page<=0} onClick={()=>onPage(page-1)}>Anterior</Button><span>Página {totalPages===0?0:page+1} de {totalPages}</span><Button variant="secondary" size="sm" disabled={page>=totalPages-1} onClick={()=>onPage(page+1)}>Próxima</Button></div>}

export function Modal({open,title,description,children,footer,onClose,size='md'}:{open:boolean;title:string;description?:string;children:ReactNode;footer?:ReactNode;onClose:()=>void;size?:'sm'|'md'|'lg'}){useEffect(()=>{if(!open)return;const h=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',h);return()=>document.removeEventListener('keydown',h)},[open,onClose]);if(!open)return null;return <div className="lf-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className={`lf-modal ${size==='sm'?'lf-modal-sm':size==='lg'?'lf-modal-lg':''}`} role="dialog" aria-modal="true" aria-label={title}><div className="lf-modal-header"><div style={{flex:1}}><h2 className="lf-modal-title">{title}</h2>{description&&<p className="lf-modal-description">{description}</p>}</div><IconButton label="Fechar" onClick={onClose}>×</IconButton></div><div className="lf-modal-body">{children}</div>{footer&&<div className="lf-modal-footer">{footer}</div>}</div></div>}
export function Drawer({open,title,description,children,footer,onClose}:{open:boolean;title:string;description?:string;children:ReactNode;footer?:ReactNode;onClose:()=>void}){useEffect(()=>{if(!open)return;const h=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',h);return()=>document.removeEventListener('keydown',h)},[open,onClose]);if(!open)return null;return <><div className="lf-drawer-backdrop" onClick={onClose}/><aside className="lf-drawer" role="dialog" aria-modal="true" aria-label={title}><div className="lf-drawer-header"><div style={{display:'flex',gap:10}}><div style={{flex:1}}><h2 className="lf-modal-title">{title}</h2>{description&&<p className="lf-modal-description">{description}</p>}</div><IconButton label="Fechar" onClick={onClose}>×</IconButton></div></div><div className="lf-drawer-body">{children}</div>{footer&&<div className="lf-drawer-footer">{footer}</div>}</aside></>}

type Toast={id:number;type:'success'|'error'|'info';title:string;message?:string};
const ToastContext=createContext<{push:(type:Toast['type'],title:string,message?:string)=>void}>({push:()=>{}});
export function ToastProvider({children}:{children:ReactNode}){const [items,setItems]=useState<Toast[]>([]);const push=useCallback((type:Toast['type'],title:string,message?:string)=>{const id=Date.now()+Math.random();setItems(v=>[...v,{id,type,title,message}]);setTimeout(()=>setItems(v=>v.filter(i=>i.id!==id)),type==='error'?7000:4500)},[]);return <ToastContext.Provider value={{push}}>{children}<div className="lf-toast-stack" aria-live="polite">{items.map(t=><div key={t.id} className={`lf-toast ${t.type}`}><div className="lf-toast-title">{t.title}</div>{t.message&&<div className="lf-toast-message">{t.message}</div>}</div>)}</div></ToastContext.Provider>}
export const useToast=()=>useContext(ToastContext);
