import React, { useEffect, useState } from 'react';
import { interactionApi, leadApi, ApiError } from '../../services/api';
import { channelLabels, interactionTypeLabels, fmtNumber } from '../../services/format';
import type { InteractionChannel, InteractionResponse, InteractionType, LeadSummary, ScorePreviewResponse } from '../../types';
import { Button, Card, Drawer, Field, Select, Textarea, useToast } from '../ui';
const channels=Object.keys(channelLabels) as InteractionChannel[]; const types=Object.keys(interactionTypeLabels) as InteractionType[];
export function InteractionForm({open,onClose,onSaved,presetLeadId}:{open:boolean;onClose:()=>void;onSaved:(v:InteractionResponse)=>void;presetLeadId?:number}){
 const toast=useToast();const [leads,setLeads]=useState<LeadSummary[]>([]);const [leadId,setLeadId]=useState('');const [channel,setChannel]=useState<InteractionChannel>('PHONE');const [type,setType]=useState<InteractionType>('FIRST_CONTACT');const [notes,setNotes]=useState('');const [preview,setPreview]=useState<ScorePreviewResponse|null>(null);const [saving,setSaving]=useState(false);
 useEffect(()=>{if(!open)return;leadApi.list({size:100,sort:'name,asc'}).then(p=>setLeads(p.content)).catch(()=>setLeads([]));setLeadId(presetLeadId?String(presetLeadId):'');setNotes('')},[open,presetLeadId]);
 useEffect(()=>{if(!open||!leadId){setPreview(null);return;} interactionApi.preview(Number(leadId),type).then(setPreview).catch(()=>setPreview(null))},[open,leadId,type]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const saved=await interactionApi.create({leadId:Number(leadId),channel,type,notes:notes.trim()||null});toast.push('success','Interação registrada',`${saved.leadName}: ${saved.scoreApplied>=0?'+':''}${saved.scoreApplied} ponto(s)`);onSaved(saved);onClose()}catch(e){toast.push('error','Não foi possível registrar',(e as ApiError).message)}finally{setSaving(false)}};
 return <Drawer open={open} title="Registrar interação" description="Registre a atividade comercial. A pontuação definitiva será calculada pelo servidor." onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button type="submit" form="interaction-form" disabled={saving||!leadId}>{saving?'Registrando...':'Registrar interação'}</Button></>}><form id="interaction-form" onSubmit={submit} style={{display:'grid',gap:16}}><Field label="Lead"><Select required disabled={!!presetLeadId} value={leadId} onChange={e=>setLeadId(e.target.value)}><option value="">Selecione um Lead</option>{leads.map(l=><option key={l.id} value={l.id}>{l.name} — {l.branchName}</option>)}</Select></Field><div className="lf-form-grid"><Field label="Canal"><Select value={channel} onChange={e=>setChannel(e.target.value as InteractionChannel)}>{channels.map(c=><option key={c} value={c}>{channelLabels[c]}</option>)}</Select></Field><Field label="Tipo"><Select value={type} onChange={e=>setType(e.target.value as InteractionType)}>{types.map(t=><option key={t} value={t}>{interactionTypeLabels[t]}</option>)}</Select></Field></div><Field label="Observação"><Textarea value={notes} maxLength={3000} rows={6} onChange={e=>setNotes(e.target.value)} /><span className="lf-helper">{notes.length}/3000 caracteres</span></Field>{preview&&<Card className="lf-preview-card"><div className="lf-card-title">Prévia da pontuação</div><div className="lf-metric-grid"><div><div className="lf-mini-label">Regra</div><div className="lf-mini-value" style={{fontSize:13}}>{preview.ruleName??'Nenhuma regra ativa'}</div></div><div><div className="lf-mini-label">Pontuação atual</div><div className="lf-mini-value">{fmtNumber(preview.currentScore)}</div></div><div><div className="lf-mini-label">Após registro</div><div className="lf-mini-value">{fmtNumber(preview.projectedScore)}</div></div></div><div className="lf-helper" style={{marginTop:10}}>Variação estimada: {preview.scoreDelta>=0?'+':''}{preview.scoreDelta}</div></Card>}</form></Drawer>
}
