import React, { useEffect, useState } from 'react';
import { leadApi, taskApi, userApi, ApiError } from '../../services/api';
import type { LeadSummary, TaskResponse, UserResponse } from '../../types';
import { Button, Drawer, Field, Input, Select, Textarea, useToast } from '../ui';
import { useAuth } from '../../app/AuthContext';
function localInput(iso?:string){const d=iso?new Date(iso):new Date(Date.now()+3600000);const pad=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
export function TaskForm({open,onClose,onSaved,presetLeadId,task}:{open:boolean;onClose:()=>void;onSaved:(v:TaskResponse)=>void;presetLeadId?:number;task?:TaskResponse|null}){
 const toast=useToast();const {user}=useAuth();const [leads,setLeads]=useState<LeadSummary[]>([]);const [sellers,setSellers]=useState<UserResponse[]>([]);const [form,setForm]=useState({title:'',description:'',leadId:'',responsibleUserId:'',dueAt:localInput()});const [saving,setSaving]=useState(false);
 useEffect(()=>{if(!open)return;leadApi.list({size:100,sort:'name,asc'}).then(p=>setLeads(p.content)).catch(()=>setLeads([])); if(task)setForm({title:task.title,description:task.description??'',leadId:String(task.leadId),responsibleUserId:String(task.responsibleUserId),dueAt:localInput(task.dueAt)});else setForm({title:'',description:'',leadId:presetLeadId?String(presetLeadId):'',responsibleUserId:'',dueAt:localInput()})},[open,presetLeadId,task]);
 useEffect(()=>{const lead=leads.find(l=>l.id===Number(form.leadId));if(!lead)return;if(user?.role==='SELLER')setSellers([]);else userApi.sellers(lead.branchId).then(setSellers).catch(()=>setSellers([]));if(!task&&!form.responsibleUserId)setForm(f=>({...f,responsibleUserId:String(lead.responsibleUserId)}))},[form.leadId,leads,task,user]);
 const set=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const payload={title:form.title.trim(),description:form.description.trim()||null,responsibleUserId:form.responsibleUserId?Number(form.responsibleUserId):null,dueAt:new Date(form.dueAt).toISOString()};const saved=task?await taskApi.update(task.id,payload):await taskApi.create({...payload,leadId:Number(form.leadId)});toast.push('success',task?'Tarefa atualizada':'Tarefa criada com sucesso',saved.title);onSaved(saved);onClose()}catch(e){toast.push('error','Não foi possível salvar',(e as ApiError).message)}finally{setSaving(false)}};
 return <Drawer open={open} title={task?'Editar tarefa':'Nova tarefa'} description="Organize o próximo passo comercial e defina o responsável." onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button type="submit" form="task-form" disabled={saving}>{saving?'Salvando...':'Salvar tarefa'}</Button></>}><form id="task-form" onSubmit={submit} style={{display:'grid',gap:16}}><Field label="Título"><Input required maxLength={180} value={form.title} onChange={e=>set('title',e.target.value)}/></Field><Field label="Lead"><Select required disabled={!!presetLeadId||!!task} value={form.leadId} onChange={e=>set('leadId',e.target.value)}><option value="">Selecione</option>{leads.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</Select></Field><Field label="Responsável">{user?.role==='SELLER'?<Input value={user.name} readOnly/>:<Select value={form.responsibleUserId} onChange={e=>set('responsibleUserId',e.target.value)}><option value="">Responsável atual do Lead</option>{sellers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select>}</Field><Field label="Data e horário"><Input required type="datetime-local" value={form.dueAt} onChange={e=>set('dueAt',e.target.value)}/></Field><Field label="Observação"><Textarea maxLength={3000} rows={5} value={form.description} onChange={e=>set('description',e.target.value)}/></Field></form></Drawer>
}
